### ISSUE TITLE
请问这个库支持ios吗？

### ISSUE THREAD

**Issue by lanten** [ZScholes18/rn-echarts#13]

**Comment by ZScholes18** [comment]
https://github.com/ZScholes18/rn-echarts-zzs/blob/master/chartView.js
第80行改成
```javascript
source = require('./assets/index.html');
```
应该可以，我还没在ios上测过

http://www.tuicool.com/articles/fM3yyq 请参考这篇文章

**Comment by xpbtmusic** [comment]
` getUri() {
        let source;
        if (__DEV__) {
            source = {uri: (Platform.OS === 'ios' ? 'assets/' : 'file:///android_asset/') + 'index.html'};
        } else {
            source = {uri: (Platform.OS === 'ios' ? 'assets/' : 'file:///android_asset/') + 'index.html'};
        }

        return source;
    }`
assets为用xcode手动添加的资源目录，

**Comment by lanten** [comment]
感谢答复，目前在调试ios时遇到其它问题，容我解决后再做尝试 😅

**Comment by lanten** [comment]
ok 
我用了@ZScholes18  提供的方法, ios 运行良好
